# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from ..core.unchecked_base_model import UnionMetadata
from .session_stream_chunk_event import SessionStreamChunkEvent
from .session_stream_chunk_final_event import SessionStreamChunkFinalEvent


class SessionStepStreamChunk_Event(SessionStreamChunkEvent):
    type: typing.Literal["event"] = "event"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class SessionStepStreamChunk_FinalEvent(SessionStreamChunkFinalEvent):
    type: typing.Literal["final_event"] = "final_event"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


SessionStepStreamChunk = typing_extensions.Annotated[
    typing.Union[SessionStepStreamChunk_Event, SessionStepStreamChunk_FinalEvent], UnionMetadata(discriminant="type")
]
